name: Get News

on:
  schedule:    
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          feedparser

    - name: pull news
      run: python getnews.py

    - name: push
      run: |
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git add *
        git commit -m "sync"
        git push
